
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import ttu.idu0080.order.server.model.EshopOrder;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-05-15T22:21:34.257+03:00
 * Generated source version: 3.1.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "file:/C:/Users/Smarta/Documents/Veebiteenused/ariprotsessi_ylesande_lsamaterjalid/5/ProductServiceClientServiceClient_naide/MyProductService/WebContent/wsdl/orders.wsdl",
                      endpointInterface = "ttu.idu0080.order.server.OrderService")
                      
public class OrderServicePortImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerId(int customerId)*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerId(int customerId) { 
        LOG.info("Executing operation getOrdersByCustomerId");
        System.out.println(customerId);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(551442536);
            _returnVal1Customer.setFirstName("FirstName507384857");
            _returnVal1Customer.setLastName("LastName264665299");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-503434511);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1497833565);
            _returnVal1OrderProductsVal1.setPrice(0.7849904f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.91954523f);
            _returnVal1OrderProductsVal1.setProductCount(61742837);
            _returnVal1OrderProductsVal1.setProductName("ProductName666473724");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.22557408f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(335378696);
            _returnVal1Seller.setName("Name-1938972202");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(-602676316);
            _returnVal1ShippingAddress.setCountry("Country-1885236842");
            _returnVal1ShippingAddress.setCounty("County-1887124133");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1583497065");
            _returnVal1ShippingAddress.setTownVillage("TownVillage651077064");
            _returnVal1ShippingAddress.setZipcode("Zipcode2093795652");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getAllOrders()*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getAllOrders() { 
    	LOG.info("Executing operation getAllOrders");
        try {
        	EntityManagerFactory factory = Persistence.createEntityManagerFactory("ProductService");
        	EntityManager em = factory.createEntityManager();
        	
        	List<Order> orders = new ArrayList<Order>();
        	
        	List<EshopOrder> eshopOrders = em.createNamedQuery("EshopOrder.findAll").getResultList();
        	for (EshopOrder eo : eshopOrders) {
        		Order order = new Order();
        		
        		ttu.idu0080.order.server.Customer customer = new Customer();
            	customer.setCustomer((int) eo.getCustomerFk().getCustomer());
            	customer.setFirstName(eo.getCustomerFk().getFirstName());
            	customer.setLastName(eo.getCustomerFk().getLastName());
            	order.setCustomer(customer);
            	
            	order.setOrderId((int) eo.getEshopOrder());
            	order.setPriceTotal(eo.getPriceTotal().floatValue());
            	            
                ttu.idu0080.order.server.Seller seller = new Seller();
                seller.setEnterprise((int) eo.getSeller().getEnterprise());
                seller.setName(eo.getSeller().getFullName());
                List<ttu.idu0080.order.server.model.EntAddress> addresses = em.createQuery("SELECT e FROM EntAddress e WHERE e.subjectFk = :enterprise")
            	        .setParameter("enterprise", BigDecimal.valueOf(eo.getSeller().getEnterprise()))
            	        .getResultList();
                for (ttu.idu0080.order.server.model.EntAddress a : addresses) { seller.getAddresses().add(addressBuilder(a)); }
            	
            	order.setSeller(seller);
            	
            	ttu.idu0080.order.server.Address address = new Address();
            	address.setAddress((int) eo.getShippingAddressFk().getAddress());
            	address.setCountry(eo.getShippingAddressFk().getCountry());
            	address.setCounty(eo.getShippingAddressFk().getCounty());
            	address.setStreetAddress(eo.getShippingAddressFk().getStreetAddress());
            	address.setTownVillage(eo.getShippingAddressFk().getTownVillage());
            	address.setZipcode(eo.getShippingAddressFk().getZipcode());
            	order.setShippingAddress(address);
            	
            	orders.add(order);
        	}
        	
        	em.close();
			factory.close();
        	
            return orders;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    
    public ttu.idu0080.order.server.EntAddress addressBuilder(ttu.idu0080.order.server.model.EntAddress entAddress) {
        ttu.idu0080.order.server.EntAddress ea = new EntAddress();
        ea.setAddress((int) entAddress.getEntAddress());
        ea.setCountry(entAddress.getCountry());
        ea.setCounty(entAddress.getCounty());
        ea.setStreetAddress(entAddress.getStreetAddress());
        ea.setTownVillage(entAddress.getTownVillage());
        ea.setZipcode(entAddress.getZipcode());
        return ea;
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByOrderId(int orderId)*
     */
    public ttu.idu0080.order.server.Order getOrdersByOrderId(int orderId) { 
        LOG.info("Executing operation getOrdersByOrderId");
        System.out.println(orderId);
        try {
            ttu.idu0080.order.server.Order _return = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnCustomer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnCustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            ttu.idu0080.order.server.Address _returnCustomerAddressesVal1 = new ttu.idu0080.order.server.Address();
            _returnCustomerAddressesVal1.setAddress(1171901807);
            _returnCustomerAddressesVal1.setCountry("Country-336194309");
            _returnCustomerAddressesVal1.setCounty("County-834563963");
            _returnCustomerAddressesVal1.setStreetAddress("StreetAddress1660065589");
            _returnCustomerAddressesVal1.setTownVillage("TownVillage-1543324034");
            _returnCustomerAddressesVal1.setZipcode("Zipcode-1470102099");
            _returnCustomerAddresses.add(_returnCustomerAddressesVal1);
            _returnCustomer.getAddresses().addAll(_returnCustomerAddresses);
            _returnCustomer.setCustomer(-1637228355);
            _returnCustomer.setFirstName("FirstName-449408455");
            _returnCustomer.setLastName("LastName1995550066");
            _return.setCustomer(_returnCustomer);
            _return.setOrderId(1163706448);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnOrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnOrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnOrderProductsVal1.setOrderProduct(1091740753);
            _returnOrderProductsVal1.setPrice(0.955693f);
            _returnOrderProductsVal1.setPriceTotal(0.66024214f);
            _returnOrderProductsVal1.setProductCount(-1341055589);
            _returnOrderProductsVal1.setProductName("ProductName-2077620552");
            _returnOrderProducts.add(_returnOrderProductsVal1);
            _return.getOrderProducts().addAll(_returnOrderProducts);
            _return.setPriceTotal(0.18254417f);
            ttu.idu0080.order.server.Seller _returnSeller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnSellerAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnSellerAddressesVal1.setAddress(-221606799);
            _returnSellerAddressesVal1.setCountry("Country1039862842");
            _returnSellerAddressesVal1.setCounty("County1418821128");
            _returnSellerAddressesVal1.setStreetAddress("StreetAddress-155154728");
            _returnSellerAddressesVal1.setTownVillage("TownVillage-392675575");
            _returnSellerAddressesVal1.setZipcode("Zipcode-1522438359");
            _returnSellerAddresses.add(_returnSellerAddressesVal1);
            _returnSeller.getAddresses().addAll(_returnSellerAddresses);
            _returnSeller.setEnterprise(122612924);
            _returnSeller.setName("Name-589782025");
            _return.setSeller(_returnSeller);
            ttu.idu0080.order.server.Address _returnShippingAddress = new ttu.idu0080.order.server.Address();
            _returnShippingAddress.setAddress(1686825258);
            _returnShippingAddress.setCountry("Country1609764165");
            _returnShippingAddress.setCounty("County1527225271");
            _returnShippingAddress.setStreetAddress("StreetAddress-1348518570");
            _returnShippingAddress.setTownVillage("TownVillage-2127049189");
            _returnShippingAddress.setZipcode("Zipcode-1752406496");
            _return.setShippingAddress(_returnShippingAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByShippingAddress(java.lang.String country, java.lang.String county)*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByShippingAddress(java.lang.String country, java.lang.String county) { 
        LOG.info("Executing operation getOrdersByShippingAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(144855177);
            _returnVal1Customer.setFirstName("FirstName803198991");
            _returnVal1Customer.setLastName("LastName1787235908");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1824161772);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(-201456656);
            _returnVal1OrderProductsVal1.setPrice(0.6876849f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.7393443f);
            _returnVal1OrderProductsVal1.setProductCount(-1574567014);
            _returnVal1OrderProductsVal1.setProductName("ProductName-260113248");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.18378234f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(-2121192763);
            _returnVal1Seller.setName("Name-621856804");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(-519286202);
            _returnVal1ShippingAddress.setCountry("Country-90840351");
            _returnVal1ShippingAddress.setCounty("County577796662");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-456084344");
            _returnVal1ShippingAddress.setTownVillage("TownVillage1278483658");
            _returnVal1ShippingAddress.setZipcode("Zipcode-809878501");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerLastName(java.lang.String lastName)*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerLastName(java.lang.String lastName) { 
        LOG.info("Executing operation getOrdersByCustomerLastName");
        System.out.println(lastName);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(604240538);
            _returnVal1Customer.setFirstName("FirstName1976949990");
            _returnVal1Customer.setLastName("LastName1540150229");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(874344863);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(-336538313);
            _returnVal1OrderProductsVal1.setPrice(0.7979655f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.49924672f);
            _returnVal1OrderProductsVal1.setProductCount(1047580051);
            _returnVal1OrderProductsVal1.setProductName("ProductName1128922898");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.18795747f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1720169399);
            _returnVal1Seller.setName("Name-860696412");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(-2139386222);
            _returnVal1ShippingAddress.setCountry("Country1716934303");
            _returnVal1ShippingAddress.setCounty("County-855983674");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1047769358");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1729935517");
            _returnVal1ShippingAddress.setZipcode("Zipcode-356229043");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
