
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import ttu.idu0080.order.server.model.OrderShipment;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-05-15T22:22:01.698+03:00
 * Generated source version: 3.1.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderShipmentServiceService",
                      portName = "OrderShipmentServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "file:/C:/Users/Smarta/Documents/Veebiteenused/ariprotsessi_ylesande_lsamaterjalid/5/ProductServiceClientServiceClient_naide/MyProductService/WebContent/wsdl/order_shipments_1.wsdl",
                      endpointInterface = "ttu.idu0080.order.server.OrderShipmentService")
                      
public class OrderShipmentServicePortImpl implements OrderShipmentService {

    private static final Logger LOG = Logger.getLogger(OrderShipmentServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderShipmentService#getOrderShipmentsByOrderIdRyhmName(int orderId, java.lang.String ryhmName)*
     */
    public java.util.List<ttu.idu0080.order.server.OrderShipment> getOrderShipmentsByOrderIdRyhmName(int orderId, java.lang.String ryhmName) { 
        LOG.info("Executing operation getOrderShipmentsByOrderIdRyhmName");
        System.out.println(orderId);
        System.out.println(ryhmName);
        try {
        	EntityManagerFactory factory = Persistence.createEntityManagerFactory("ProductService");
        	EntityManager em = factory.createEntityManager();
        	
        	List<ttu.idu0080.order.server.model.OrderShipment> orderShipments = em.createNamedQuery("OrderShipment.findByOrderIdAndRyhmName")
        			.setParameter("orderFk", BigDecimal.valueOf(orderId))
        			.setParameter("ryhmName", ryhmName)
        	        .getResultList();
        	
        	List<ttu.idu0080.order.server.OrderShipment> newOrderShipments = new ArrayList<ttu.idu0080.order.server.OrderShipment>();
        	
        	for (OrderShipment os : orderShipments) {
        		ttu.idu0080.order.server.OrderShipment newOs = new ttu.idu0080.order.server.OrderShipment();
        		
        		GregorianCalendar gc = new GregorianCalendar();
        		gc.setTime(os.getApproxDeliveryDate());
        		XMLGregorianCalendar xmlDate = DatatypeFactory.newInstance().newXMLGregorianCalendar(gc);
        		newOs.setApproxDeliveryDate(xmlDate);
        		
        		newOs.setCourierName(os.getCourierName());
        		newOs.setOrder(os.getOrderFk().intValue());
        		newOs.setOrderShipment((int) os.getOrderShipment());
        		newOs.setRyhmName(os.getRyhmName());
        		newOs.setShippingPrice(os.getShippingPrice().setScale(2, RoundingMode.HALF_EVEN).longValue());
        		newOs.setTrackingNumber(os.getTrackingNumber());
        		
        		newOrderShipments.add(newOs);
        	}
        	
        	em.close();
			factory.close();
        	
        	return newOrderShipments;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderShipmentService#insertOrderShipment(int orderId, java.lang.String ryhmName, java.lang.String trackingNumber, java.lang.String courierName, javax.xml.datatype.XMLGregorianCalendar approxDeliveryDate, double shippingPrice)*
     */
    public int insertOrderShipment(int orderId, java.lang.String ryhmName, java.lang.String trackingNumber, java.lang.String courierName, javax.xml.datatype.XMLGregorianCalendar approxDeliveryDate, double shippingPrice) { 
        LOG.info("Executing operation insertOrderShipment");
        System.out.println(orderId);
        System.out.println(ryhmName);
        System.out.println(trackingNumber);
        System.out.println(courierName);
        System.out.println(approxDeliveryDate);
        System.out.println(shippingPrice);
        try {
            int _return = 1246487109;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
